### ISSUE TITLE
Tutorial 1 - Kamerapositionen anpassen

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#105]
Im Tutorial kommt es oft vor, dass sich nach Erledigung eines Schritts die Kamera automatisch an eine andere Stelle der Karte bewegt, da hier ein Text-Popup erschienen ist.
Allerdings passiert es dabei oft, dass die Positionierung nicht optimal ist und man nicht das gesamte Text Pop-Up sieht. 
Man muss da dann per rechtem Stick scrollen/anpassen, damit man den Text komplett sieht.
Das ist etwas unrund.

Bitte schaut euch auch die anderen Tutorials an, ob das bei denen auch passiert.

**Comment by michaelblatz** [comment]
Tutorial 2 hatte ebenfalls 2 Stellen. Tutorial 3 war kameraseitig in Ordnung.
