### ISSUE TITLE
Tutorial - man öffnet oft das Einstellungsmenü

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#110]
Wenn man ein Tutorial startet, dann wird der virtuelle Cursor intern in der Nähe des Optionen-Buttons platziert. (Aber grafisch nicht auf dem Screen dargestellt.)
Wenn man also im ersten Tutorial-Schritt den "A"-Button drücken soll, dann wird automatisch immer das Ingame-Menü geöffnet.

1. Den virtuellen Cursor grafisch mit anzeigen.
2. Den virtuellen Cursor auf eine Stelle platzieren, wo man keine Aktion ausführt.

**Comment by michaelblatz** [comment]
Der Cursor wird nun im Tutorial immer auf die Bildschirmmitte gesetzt, sobald der Cursor sichtbar wird. In allen 3 Tutorials waren hier keine kritischen Elemente
