### ISSUE TITLE
Switch, Menü "Spielerauswahl"- Namensänderung nicht möglich / Controllersteuerung weg

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#116]
Menü "Spielerauswahl".
Wenn man in der PC-Version auf den Namen einer Figur eines menschlichen Spielers klickt, dann wird der Namen markiert und man kann mit der Tastatur einen anderen Namen eingeben.

In der Switch-Version wird der Name nach auch markiert angezeigt, aber es wird nicht das Applet zur Namenseingabe geöffnet.
Zusätzlich wird in diesem Zustand die Controller-Steuerung deaktiviert und man kann das Menü nur noch per Touch bedienen.

**Comment by PaulGuillaumonMuT** [comment]
Nicht komplett behoben.

Es wird jetzt das Tastatur Applet geöffnet und man kann einen Namen eingeben.
Aber man kann weiterhin nach der Namenseingabe nur mit Touch navigieren. Stick funktioniert nicht.

**Comment by michaelblatz** [comment]
Auch hier bräuchte ich leider nochmal etwas mehr Info. Anbei wieder ein Video von mir, bei dem das Problem nicht auftritt

**Comment by PaulGuillaumonMuT** [comment]
Kann ich auch nicht mehr nachvollziehen.
Da hat gestern wohl irgendwas mit meiner Switch und Controller an sich nicht mehr korrekt funktioniert zu haben.
Heute nach Neustart der Switch funktioniert das einwandfrei.
