### ISSUE TITLE
Menü "wähle eine Karte" - Zuordnung der Spielerportraits falsch

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#117]
Menü "wähle eine Karte".
Beim Großteil der Figuren wird nach Auswahl einer Karte ein falsche Portraitgrafik angezeigt.

Peter (Rot im Menü davor) soll wählen -> nach Umdrehen der Karte wird Shin Orange/Gelb angezeigt (falsch)
Shi (Orange/Geld im Menü davor) soll wählen -> nach dem Umdrehen der Karte wird Peter Rot angezeigt (falsch)
Sarah (Grün im Menü davor) soll wählen -> nach dem Umdrehen der Karte wird Noah Lila angezeigt (falsch)
Noah (Lila im Menü davor) soll wählen -> nach dem Umdrehen der Karte Sarah Grün angezeigt (falsch)
Oscar (Blau im Menü davor) soll wählen -> nach dem Umdrehen der Karte korrekt als Oscar Blau angezeigt. (korrekt)

James Rot -> nach Umdrehen Robin Gelb/Orange (falsch)
Robin Gelb-Orange -> nach Umdrehen James Rot (falsch)
William Grün -> nach Umdrehen Mina Lila (falsch)
Mina Lila -> William Grün (falsch)
Olivia blau -> nach Umdrehen Olivia blau (korrekt)

Bitte die Zuordnung der Grafiken im Menü "wähle eine Karte" anpassen, damit die mit den Portraits der namentlich oben angegebenen Spielfiguren übereinstimmen.

**Comment by FrederikOmlor** [comment]
Dürfte nun gefixt sein!
