### ISSUE TITLE
Ingame - Farbzuordnung unten in der Leiste der Spieler falsch

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#118]
Als Spieler ausgewählt
Peter Rot
Shin Gelb-Orange
Sarah Grün
Oscar Blau
Noah Lila

Im Spiel sind die Farbzuordnungen unten
Peter Gelb (falsch)
Shin Rot (falsch)
Sarah Schwarz (falsch)
Oscar Blau (korrekt)
Noah Grün (falsch)

Das Gleiche auch bei den anderen Spielerportrait-Varianten. Hier stimmen die Farbzuordnungen im Spiel unten auch nicht.

**Comment by FrederikOmlor** [comment]
Bitte aufgrund von Fix für #117 nochmal prüfen.
