### ISSUE TITLE
von Ravensburger - Englische "Artefakte" bei gewählter deutscher Sprache

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#126]
25.04.2024 / Peter: Viele Texte wurden überarbeitet, gibt aber immer noch englische „Artefakte“ bei gewählter deutscher Sprache.

PG: Könnt mir bitte mal gezielt durchtesten, wo überall englische Texte noch drin sind, obwohl DE als Sprache eingestellt ist.
Ich weiß auf jeden Fall eine Stelle...es gibt einen Button beim Auswahl der Controller, dort ist ein englischer Text. Hatte ich auch als Fehler gemeldet.
Aber laut der generellen Info von Ravensburger scheint es noch andere Stellen zu geben.

**Comment by michaelblatz** [comment]
habe alle Stellen nochmal durchgeschaut. Ich denke, es war wirklich nur noch der Button
