### ISSUE TITLE
von Ravensburger, Switch - "Mr. X am Zug...wegschauen" Pop-Up kann man nicht mit virtuellem Cursor bestätigen

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#133]
30.04.2024 / Peter: Starte ich ein Spiel mit mehreren menschlichen Mitspielern, dann taucht zu Beginn das Popup für Mr. X mit dem Hinweis auf, dass andere Spieler wegsehen sollen. Während dieses Popup angezeigt wird ist zwar der virtuelle Cursor zu sehen, aber ich kann diesen nicht bewegen. Ich kann das Popup nur mittels A oder B Button wegklicken/akzeptieren. Das passiert auch bei jeder weiteren Runde, wenn Mr. X an der Reihe ist.

**Comment by michaelblatz** [comment]
@PaulGuillaumonMuT Wie sollen wir hier vorgehen?
Wäre es nicht sinnvoller, den virtuellen Cursor einfach nicht anzuzeigen?

**Comment by PaulGuillaumonMuT** [comment]
Ja, gute Idee. Bitte den virtuellen Cursor in dieser Situation nicht anzeigen.
