### ISSUE TITLE
Switch, Hauptmenü - nach Extras, Regeln keine Navigation möglich im Hauptmenü

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#137]
Im Hauptmenü Extras und Regeln auswählen.
Im Regel-Menü zurück mit B.

Im Hauptmenü ist jetzt kein Button vormarkiert und man L-Stick kann man keinen Button auswählen.

**Comment by michaelblatz** [comment]
Um keine Unsicherheit zu erhalten, welche Issues im letzten Build bearbeitet waren und welche erst danach kamen, habe ich bei den neueren erledigten Issues uns beide assigned. Sobald die neuste Version kommt, nehme ich mich wieder raus
