### ISSUE TITLE
von Ravensburger - Sound bei Fähre mit Blacktickt anpassen

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#141]
07.05.24, Valentin

Bei der Fahrt mit der Fähre kommt ein Schiffsgeräusch. Man muss aber für die Fähre ein Blackticket einsetzen. Es sollte hier der gleiche Sound kommen wie bei jeder anderen Blackticket fahrt.

**Comment by michaelblatz** [comment]
Aber wieso?
Das ist so in der App vorgesehen und in der mobile Variante so drin. Ist das wirklich ein Todo?

**Comment by PaulGuillaumonMuT** [comment]
Ich kläre das mit Valentin.
Erstmal nix machen.

**Comment by PaulGuillaumonMuT** [comment]
Feedback von Ravensburger:
"Das mit dem Sound der Fähre wäre allerdings gut, wenn es geändert wird. Der Sound ist ja auch schon vorhanden. Es muss nur das Fährgeräusch raus und mit dem vorhandenen Sound ersetzt werden. Wenn es wirklich einen riesigen Auffand macht, geht es wohl auch so, aber besser wäre es, wenn es angepasst würde. Sonst können die Spieler herausfinden, wie Mr/Ms X das Blackticket eingesetzt haben und das ist Spielmechanisch so nicht gedacht."

Ich finde das macht vom spielerischen her schon Sinn, da man über das Fährgeräusch einen zusätzlichen eigentlich nicht gewünschten Hinweis auf die Position von Mr. X bekommt.

Daher sollte das geändert werden.
