### ISSUE TITLE
von Ravensburger - KI macht keinen Zug

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#142]
07.05.24, Valentin

KI gesteuerte Figur macht ihren Zug nicht. -> MR X = Spieler, 1 Detektiv = Spieler, 2 Detektiv = KI (je ein Zug) -> Dann abgebrochen und Fortgesetzt. Nun macht KI keinen Zug mehr und das Spiel geht nicht weiter. -> Dann wieder beendet und Fortgesetzt, nun macht KI ihren Zug. Ich hatte auch mehrere Spielstarts, bei denen sich das Spiel gleich zu Beginn einer neuen Partie aufgehangen hat (siehe Video).

https://github.com/Korion-Interactive/scotland-yard/assets/86236228/dc4258ce-553e-42f4-88d9-76e8cc05062a

**Comment by michaelblatz** [comment]
Konnten wir nur in seltenen Fällen reproduzieren, allerdings gab es eine Stelle beim Speichern, die eine mögliche Ursache sein könnte. Wir haben das entsprechend umgebaut und konnten den Fehler nach einer Vielzahl von Versuchen nicht mehr nachstellen. Bleibt aber unter Beobachtung.

**Comment by PaulGuillaumonMuT** [comment]
Ist bisher nicht wieder aufgetreten bei mir. Daher erstmal geschlossen.
