### ISSUE TITLE
von Ravensburger - Anzeige für verbleibende Tickets wird doppelt angezeigt

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#143]
07.05.24, Valentin

Anzeige für die verbleibenden Tickets wird bei Klick auf den Namen doppelt angezeigt, wenn sie bereits am Zug ist.

**Comment by michaelblatz** [comment]
@PaulGuillaumonMuT Gleiche Problematik erneut: In der App ist das Verhalten so vorgesehen oder mindestens genau so drin (Anbei Screenshot aus der App, den ich eben gemacht habe). Ist das also wirklich ein Todo?
![image](https://github.com/Korion-Interactive/scotland-yard/assets/42408911/3aeb9ae4-2092-4434-b15f-ec4261b94c61)

**Comment by PaulGuillaumonMuT** [comment]
Ich kläre das mit Valentin.
Erstmal nix machen.

**Comment by PaulGuillaumonMuT** [comment]
Kann so bleiben.
