### ISSUE TITLE
Probleme mit Texten - Textumbrüche (Wörter werden umgebrochen) und fehlende Sonderzeichen

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#147]
Nur auf DE getestet, daher weiß ich nicht, wie das in den anderen Sprachen ist.

Es sind keine Sonderzeichen in den Texten. 
z.B. Extras, Regeln, Allgemein...das Wort "übernehmen" wird als "bernehmen" dargestellt.

Ist mir bisher noch nie aufgefallen - evtl. ist das ein ganz neues Problem.

Viele Texte, in denen die Zeilenumbrüche nicht korrekt funktionieren, da der Zeilenumbruch direkt im Wort gemacht wird.
z.B. Extras, Regeln, Allgemein...z.B. "nächtliche" wird umgebrochen als "nchtlic" und "he".

**Comment by michaelblatz** [comment]
Das ist ein neues Problem, das bei der Konvertierung von Excel ins Format für das Spiel passiert ist. Ich muss schauen, woran das liegt, dass es dieses Mal nicht geklappt hat.
