### ISSUE TITLE
von Nintendo - File system: Storage media: 0011: Limits on frequency and amount of writing to storage media

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#150]
Problem:
The application has recorded 3 fails on the WriteAccessCount during the FS Access Log check (Logs attached).

Expected Result:
Applications cannot exceed writing to storage media more than 32 times per minute.

Procedure:
1) Launch the application.
2) Start a New Game.
3) Select "one controller to pass around".
4) Begin the round and play normally until caught.
5) Begin a new round until Mr. X escapes.
6) Exit to the main menu.
7) Observe log results. 

version 0.9.9. 13.05.2024
Bitte prüfen, ob das immer noch auftritt und ggf. beheben.

**Comment by michaelblatz** [comment]
Wichtig: Da es kaum anders geht, wurde die Anzahl der Speichervorgänge verringert. D.h. er speichert nur noch nach jedem 2. Zug. Der Verlust dürfte überschaubar schlimm sein, sollte aber ggf. mit Ravensburger kommuniziert werden.

**Comment by PaulGuillaumonMuT** [comment]
Nintendo hat den Fehler nochmal gemeldet mit folgenden Infos:
Problem:
The application exceeds the allowed write frequency.
See attached log and result files for additional information.

Expected Result:
The application must write to storage media no more than 32 times per minute.

Note:
The log file was created with the following procedure:
1. Start up the application without save data
2. Start a new game with one controller per person, playing as Mr. X and escape.
3. Start a new game with one controller per person, playing as a detective and play until Mr. X escapes.
4. On the title screen, disable the music and change the language.
5. Close the application.

Note: With the procedures provided above, the attached log was created. You can observe that the application has written to storage media more than 32 times per minute on 11 occasions.

[HAC-P-BHL7A 00.01 log.zip](https://github.com/user-attachments/files/15612949/HAC-P-BHL7A.00.01.log.zip)

Ich frage dafür aber erstmal einen Waiver an, da es aus meiner Sicht ja schon ein Problem ist, wenn wir die Anzahl der Speichervorgänge nur jeden 3. oder 4. Zug machen.

**Comment by michaelblatz** [comment]
Ich konnte feststellen, dass das Game Setup mitgespeichert wurde, obwohl sich daran nichts ändert (Das Sind Dinge wie die Startstationen oder der gewählte Spielmodus). Das habe ich aus allen Speicherbefehlen rausgenommen, sodass beim Speichern immer nur ein Dateizugriff erfolgt und nicht stetig 2. Das müsste es auch nochmal deutlich reduzieren
