### ISSUE TITLE
von Nintendo - General Bug: Lockup during the BASICS tutorial

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#151]
Detail:
A lockup occurs during the BASICS tutorial after the player completes the segment on how movement tickets are used where the cursor becomes stuck and no further input is accepted. This issue occurred in 5 out of 5 attempts.
Procedures:
1. Start the application.
2. Select NEW GAME.
3. Select TUTORIAL.
4. Select the BASICS tutorial.
5. Progress through the tutorial until prompted to use a taxi ticket to station 174.
6. Notice the above-mentioned issue. 

version 0.9.9. 13.05.2024
Bitte prüfen, ob das immer noch auftritt und ggf. beheben.

**Comment by michaelblatz** [comment]
Konnte ich weder in der aktuellen, noch in 1.0.0 nachstellen. Hoffe daher, dass es gelöst ist
