### ISSUE TITLE
Nintendo - General Bug: Lockup during the DETECTIVE tutorial

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#152]
Detail:
A lockup occurs during the DETECTIVE tutorial after the player moves to station 56 where the cursor becomes stuck and no further input is accepted. This issue occurred in 5 out of 5 attempts.
Procedures:
1. Start the application.
2. Select NEW GAME.
3. Select TUTORIAL.
4. Select the DETECTIVE tutorial.
5. Progress through the tutorial and move to station 56.
6. Wait for the computer players to move.
7. When prompted to move to station 42, notice the above-mentioned issue.

version 0.9.9. 13.05.2024
Bitte prüfen, ob das immer noch auftritt und ggf. beheben.

**Comment by michaelblatz** [comment]
Konnte ich weder in der aktuellen, noch in 1.0.0 nachstellen. Hoffe daher, dass es gelöst ist
