### ISSUE TITLE
nochmal neues Lokafile einbauen

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#166]
Es gab noch eine DE-Textanpassung, die für die Freigabe von Ravensburger gemacht werden muss.
Daher bitte dieses File verwenden.

[Loka Scotland Yard - Ravensburger Bugfixes.xlsx](https://github.com/user-attachments/files/15510121/Loka.Scotland.Yard.-.Ravensburger.Bugfixes.xlsx)

Die anderen Tickets mit den vorherigen Versionen des Lokafiles zum Importieren habe ich geschlossen, damit das nicht zu verwirrend wird.

Geändert wurde der fett markierte Text

"Mister X muss sich zeigen, wenn einer der Detektive auf sein Feld rückt oder er keine Möglichkeiten mehr zur Flucht hat. **Dann haben die Detektive gewonnen. Mister X wurde gefasst.**

Bleibt Mister X allerdings bis zum 22. Zug unentdeckt, so gewinnt er. (Achtung: Es handelt sich um 22 KOMPLETTE Spielzüge. Aufgrund der Doppelzugtickets kann Mister X dabei allerdings 24 STATIONEN besucht haben!)"

Vorher war da ein Sonderzeichen mit enthalten, dass im Spiel nicht korrekt dargestellt wurde.
Dieses Sonderzeichen wurde nur an dieser einen Textstelle im Lokakit verwendet.
Daher wurde das Problem durch eine Textänderung behoben und nicht durch codeseitiges Bugfixing.

**Comment by michaelblatz** [comment]
@PaulGuillaumonMuT Ich habe entdeckt, dass ein neuer Key eingebaut wurde, der gelb markiert ist: "tutorial_general_1_PS"
Die andere Textzeile mit "Knopf" ist unter dem key "tutorial_general_1" zu finden. Diese Zeile ist aber rot markiert.

Hier verstehe ich noch nicht ganz, was zu tun ist: Soll ich den Key "tutorial_general_1" mit dem "tutorial_general_1_PS" austauschen? (In dem Fall würde ich lieber den Text von "tutorial_general_1_PS" in  die Zeile von "tutorial_general_1" einfügen) oder soll ich hier eine Fallunterscheidung machen zwischen PlayStation und den anderen Plattformen?

**Comment by PaulGuillaumonMuT** [comment]
Bitte eine Fallunterscheidung machen.

Den Key 
tutorial_general_1_PS
nur für die PlayStation-Versionen verwenden.

 "tutorial_general_1"
für Switch und PC verwenden.
