### ISSUE TITLE
von Nintendo - General Bug: Missing cursor when reloading session

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#167]
Problem:
Upon reloading a session the user's in-game cursor is not displayed anymore, resulting in the user to be required to use touch screen operations in order to continue playing the session. The cursor can be displayed again by tapping on the options menu symbol in the upper bar via touch screen operations. However, the user will not be able to operate the options menu with the cursor anymore.

Procedure:
1. Start a new session.
2. Wait until every player made one action and then exit the session via the pause menu.
3. On the main menu select "RESUME".
4. In the session notice that the in-game cursor is not displayed anymore.

Note:
Please note that this is only an example and there might be more instances of similar issues being present throughout the application.

Bitte prüfen, ob das auch für PS4, PS5, PC relevant ist!

**Comment by michaelblatz** [comment]
Bin guter Dinge, dass hier PS und Switch gleichzeitig gelöst werden
https://github.com/Korion-Interactive/scotland-yard/issues/161
