### ISSUE TITLE
von Nintendo - General Bug: Controller order in offline multiplayer

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#168]
Problem:
In the application it might happen that a player has no more possible moves, what seemingly is equal to losing and thus dropping out the game. However, if this happens in an offline multiplayer game this interferes with the controller assignment, because regardless of which player is still participating in the session, all controllers will rotate through the remaining player characters.

Example:
In an offline 4 player session it is the turn of player 3 and player 4 already dropped out of the game, since no more moves were available. After the turn of player 3 it should be player 1's turn and thus the controller of player 1 should be still assigned to the character of player 1. However, instead the application still rotates through all controllers, meaning that next not the controller of player 1 will be assigned to the character of player 1 but instead the controller of the dropped out player 4.

Bitte prüfen, ob das auch für PS4, PS5, PC relevant ist!

**Comment by michaelblatz** [comment]
Das war in der Tat ein Problem für alle Plattformen, das in diesen Grenzfällen aufgetreten ist. Ist entsprechend auch für alle Plattformen gelöst
