### ISSUE TITLE
von Nintendo - Prohibition of forcing the user to change play modes: TV mode

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#170]
Problem:
In the "Basics" tutorial in French, Italian and Spanish, the user is instructed to use their fingers to zoom in and zoom out (forcing them to undock the Nintendo Switch system to progress in the tutorial).

Expected Result:
The user should not be required or instructed to change play modes in order to progress through the core content of the application's supported play modes.

Procedure:
1. Start up the application in TV mode.
2. On the title screen, change the language to either French, Italian or Spanish.
3. Select "New Game > Tutorial > Basics".
4. Progress through the tutorial until instructed to zoom out.
5. Observe that in these three aforementioned languages, the user is prompted to use fingers to zoom out and is not provided with any other way to progress.
6. The same issue occurs when the user is prompted to zoom in afterwards.

Notes:
- The user can zoom out with the ZL Button and zoom in with the ZR Button (if they know about it). However, the tutorial provides the button prompts only in English and German. In French, Italian and Spanish, the buttons are not referenced at all and instead, touch screen operations instructions are provided (forcing the user to undock the Nintendo Switch system to progress).
- Please refer to the attached screenshots for reference.

**Comment by michaelblatz** [comment]
@PaulGuillaumonMuT Dieser Fehler ist eine Loka-Problematik und kein Code-Problem. Die Buttonbezeichner wurden von den Übersetzern wohl nicht mit übernommen

**Comment by PaulGuillaumonMuT** [comment]
Genau. Das wollte ich mir anschauen, daher hatte ich das Ticket bereits mir zugewiesen.

**Comment by PaulGuillaumonMuT** [comment]
Hier das Lokakit mit den entsprechend angepassten Texten.
[20240606 Loka Scotland Yard - Ravensburger Bugfixes.xlsx](https://github.com/user-attachments/files/15613559/20240606.Loka.Scotland.Yard.-.Ravensburger.Bugfixes.xlsx)
