### ISSUE TITLE
von Nintendo - General Bug: Using Joy-Con controllers in TV mode and tabletop mode

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#171]
Problem:
When users play the application using Joy-Con controllers in dual-controller grip in TV mode or tabletop mode, flicking the Left Stick left or right does not work in the menus.

Procedure:
1. Start up the application in TV mode or tabletop mode, using detached Joy-Con controllers in dual-controller grip.
2. On the title screen, move the Left Stick to select either "Options" or "Extras".
3. Observe that the options are not selected.

Notes:
- This issue only occurs when using Joy-Con controllers. When using the Nintendo Switch Pro Controller. the user can properly select options with the Left Stick.
- To solve this issue, the user is forced to use the directional buttons to navigate left and right in the menus.
- The issue does not occur during gameplay (the cursor can be properly moved with the Left Stick using Joy-Con controllers).
- On the player selection screen, if the user moves the Left Stick to the right when using Joy-Con controllers, the next screen is selected instead (as if the player had pressed the + Button).
- The list above is not exhaustive. Please make sure that Joy-Con controllers can be used properly in the application if they are officially supported by the application.

**Comment by michaelblatz** [comment]
@PaulGuillaumonMuT Es wäre ganz toll, wenn du das nochmal auf deinem Gerät (solltest du gerade eines zur Verfügung haben) gegentesten kannst. Ich habe es selbst getestet und auch Chris nochmal testen lassen. Bei uns sieht das Verhalten in Ordnung aus.

**Comment by PaulGuillaumonMuT** [comment]
Ich hab das auf 2 Switch Testkits getestet.

1. Testlauf - Switch A
Gerät ohne Joy-Cons gebootet. Joy-Cons synchronisiert. App im Tabletop-Mode gestartet. Im Hauptmenü funktionierten die Joy-Cons einwandfrei.

2. Testlauf - Switch B
Gerät mit Joy-Cons gebootet.
Da ich hier nicht mehr genau wusste, welche Version drauf ist...Version deinstalliert. Savegame deinstalliert. Aktuellste Switch-Version installiert (also nicht die, die bei Nintendo im Testing war, sondern die Version, die danach geliefert wurde, aber aufgrund der neuen Tickets von Nintendo nicht eingereicht wurde.)
Nach Installation der App Joy-Cons vom Gerät entfernt.
Synchronisiert.
App im Tabeltop-Mode gestartet.
Jetzt konnte ich auf Switch B den Fehler exakt wie von Nintendo beschrieben nachvollziehen.

3. Testlauf- Switch A
Switch mit Joy-Cons angeschlossen gebootet.
Jetzt auch auf dieser Switch App deinstalliert. Savegame gelöscht.
Aktuellste App installiert.
Joy-Cons entfernt. Synchronisiert.
App im Tabletop-Mode gestartet.
Jetzt konnte ich den Fehler auch auf Switch A exakt wie beschrieben nachvollziehen.

Kann es sein, dass es nicht auftritt, wenn man noch ein altes Savegame von einer vorherigen Version drauf hat?
Hattet ihr vorm Testen App-Version und Savegame gelöscht?

**Comment by michaelblatz** [comment]
Vielen Dank für das ausführliche Feedback!
Ich konnte das Verhalten mit der alten Version nachstellen, mit unserer aktuellen Version jedoch nicht mehr.
Auch diesen Fall habe ich nochmal von Chris zusätzlich überprüfen lassen
