### ISSUE TITLE
von Nintendo - General Bug: Reviewing previous turns

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#173]
Problem:
When users play in TV mode, they cannot scroll up and down the list of previous actions taken.

Procedure:
1. Start up the application in TV mode.
2. Start a new game and play a few turns.
3. Press the - Button to review the actions performed by every player in previous turns.
4. Observe that it is not possible to scroll up and down the list using the Joy-Con controllers or Nintendo Switch Pro Controller.

Note: It appears that the user can only scroll up and down the list using touch controls. As a result, they cannot review the actions performed by previous players (which is an issue when playing as a detective looking for Mr. X, as users may want to check the history of Mr. X turns to figure out where they might be).

**Comment by michaelblatz** [comment]
War auch ein Problem in der PlayStation-Variante, daher ebenfalls gefixt
