### ISSUE TITLE
Tutorial - Blocker im Schritt "Message Box"

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#18]
Im Tutorial 1 komme ich bis zum Schritt "Let's take a look at the message box. You will find the histroy of all moves made so far. Just tap it to expand."

1. Egal wo ich hier mit dem virtuelle Cursor draufgehe und A drücke, ich komme an dieser Stelle nicht weiter.
2. Mir ist auch nicht klar, wo die "Message Box" im UI überhaupt sein soll. Es wäre gut, wenn hier ein Highlight vorhanden wäre, damit es klar ist.

**Comment by michaelblatz** [comment]
Guter Punkt. Ich habe in meiner Mail keine Steuerung hinzugefügt. Leider hatten wir noch keine Zeit für das Anpassen der Texte. Hier ist kein Blocker, sondern lediglich ein nicht kommunizierter Aufruf, die "Minus"-Taste zu drücken.
Aus Gründen, die mit dem eingesetzten UI System zu tun haben, lässt sich die UI oben nicht mit dem virtuellen Cursor bedienen. 
Der Text müsste heißen "Press the following Button to expant: -". Diese Variante lässt sich mit dem vorliegenden UI System am besten umsetzen, da wir die Glyphe dann hinter den Text setzen können. Das fehlende Highlight ist aber bereits so auch in der App-Variante vorhanden. Das lässt sich leider nicht schnell übers Wochenende angehen. Ich schätze aber, dass es mit angepassten Texten bereits deutlicher werden sollte. Für kommende Woche war aber vorgesehen, dass überall noch Glyphs eingebaut werden.

Vielleicht eine generelle Übersicht der Steuerung:
In der UI: 
- A zum Bestätigen
- B um zum vorherigen Bildschirm zurückzukehren (Außer bei der Kartenwahl, bei der auch die App vorsieht, dass man nun nicht mehr zurück kann)
- NOCH NICHT INTEGRIERT aber für die kommende Version: Wechseln zwischen den zwei unterschiedlichen Grafiken/Karten der jeweiligen Spielerfarben 
- + zum Starten des Spiels (Geht kaum anders, da mit A alle Optionen in dem Menü gesteuert werden)

Im Spiel:
- A 
- - Auf Spielbrett (virtueller Cursor): Stelle anwählen
- - Bei geöffneter UI (z.B. Ticketfenster, Optionsmenü) Bestätigen
- B: Abbrechen/Ticketfenster schließen
- L/R: Durchschalten der Spielertabs
- ZL/ZR: Stufenloser Zoom   
- Linker Stick: Bewegen des virtuellen Cursors oder selektieren von Buttons
- Rechter Stick: Kamerabewegung auf dem Spielbrett
