### ISSUE TITLE
PC - Blocker in Starkartenauswahl

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#183]
Nach der Auswahl der Spieler (Mr. X als menschlicher Spieler) erschient das Startkarten-Menü. Und ein Pop-Up zur Erklärung.
Das Popup mit ESC-Taste schließen.
Danach kann man keine Startkarten auswählen.

**Comment by michaelblatz** [comment]
Wäre es im Falle des PC nicht sinnvoller, Popups nicht mit ESC zu schließen?
Das ganze ist eher ein Relikt aus früheren Versionen noch. Per Controller muss man auch den Button bestätigen und kann das Popup nicht "abbrechen".
Wäre es daher ok, wenn wir das ganze analog der Controllersteuerung so handhaben, dass man das Popup gar nicht erst mit ESC schließen kann?

**Comment by PaulGuillaumonMuT** [comment]
Ja. Pop-Ups mit ESC schließen kannst du gerne rausnehmen.
