### ISSUE TITLE
Ingame Menü - nicht nachvollziehbar bedienbar

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#20]
Wenn ich im Tutorial das Ingame Menü mit + aufrufe, dann kann ich dort die Menüauswahl nicht mit dem Stick bedienen und auch das vorausgewählte "Exit" nicht mit A bestätigen.
Man kommt also aktuell nicht aus dem Tutorial raus.

**Comment by PaulGuillaumonMuT** [comment]
Auch im normalen Spiel ist die Bedienung des Ingame Menüs nicht wirklich klar. Ich hab es da geschafft das Spiel zu beenden, aber irgendwie eher durch zufälliges rumdrücken.

**Comment by michaelblatz** [comment]
Hallo Paul,

das ist eines der Probleme mit den vorliegenden Grafiken. Da die Grafiken sehr dunkel sind, ist die Einfärbung der Buttons nur schwer sichtbar. Wenn man genau hinschaut, werden die Buttons selektiert. Dass  der Exit-Button als vorausgewählt erscheint, liegt am vorliegenden Button, der auch in der App-Version rot ist.
Allerdings habe ich die rote Grafik als Seketionsgrafik eingebaut. Der Kontrast ist hier nun deutlicher.
