### ISSUE TITLE
Logo - aktuelles Logo verwendet

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#22]
Das Logo auf der Switch im Hauptmenü sieht farblich deutlich blauer aus, als das Logo, dass Ravensburger US zuletzt geliefert hat. 
Auf meinem Monitor sieht das Logo deutlich türkiser aus.

Wird aktuell wirklich das zuletzt von Ravensburger gelieferte Logo
SY_refresh_LOGO_Layered.psd
verwendet?

Und gibt es in diesem PSD Files das Logo in unterschiedlichen Blautönen.

**Comment by michaelblatz** [comment]
Hallo Paul,

wir haben exakt dieses Logo verwendet. Photoshop und Laufendes Spiel gegenübergestellt zeigt auch den gleichen Farbraum
![image](https://github.com/Korion-Interactive/scotland-yard/assets/42408911/380125ba-ef91-4d35-9e45-d830ac750ba9)

**Comment by PaulGuillaumonMuT** [comment]
Dann wirkt das bei mir auf dem Switch Display einfach nur etwas anders.
Vielen Dank fürs Nachprüfen!
