### ISSUE TITLE
Player Selection - nicht klar wie es hier weiter geht

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#23]
Im Menü "Player Selection", wenn man alles eingestellt hat, wer mitspielt, Rundenzeit usw..., dann ist es nicht klar, was man für einen Button drücken muss, um zu Starten / zum nächsten Menü zu kommen.

**Comment by michaelblatz** [comment]
Es werden noch Glyphs eingebaut. Für die Version für Ravensburger mache ich aber an diese Stelle ein explizites Bild, damit es klarer wird.
