### ISSUE TITLE
Player Selection - über den CPU-Spielern Info "Normal" nicht klar

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#24]
Im Player Selection Menü steht über den CPU-Spielern der Text "Normal".
Zuerst hatte ich gedacht man kann hier die "Stärke" der CPU-Spieler einstellen.
Also so was in der Art "Einfach", "Normal", "Stark" oder so.
Aber man kann das "Normal" nicht verändern.

Was gibt also das "Normal" an?

**Comment by michaelblatz** [comment]
Noch relevant? Ist seit der letzten Version umschaltbar.

**Comment by PaulGuillaumonMuT** [comment]
confirm fixed
