### ISSUE TITLE
von Ravensburger, PC - Zoomen nicht möglich -> Blocker in Tutorial 1

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#28]
Mittels Tastatur/Maus kann man nicht rein- bzw. rauszoomen. Damit kann das (erste) Tutorial auch nicht beendet werden, da man dort als dritten Schritt zoomen muss. Am besten legt ihr das Zoomen auf das Mausrädchen und die +/- Tasten. So zumindest würde ich es erwarten.

**Comment by FrederikOmlor** [comment]
Kann nicht reproduziert werden. Das Zoomen im ersten Tutorial liegt auf dem Mausrad. Bitte beim nächstmöglichen Build nochmal testen und ggf. erneut rückmelden. Danke!

**Comment by PaulGuillaumonMuT** [comment]
Sicherheitshalber...wurde das Zoomen auch auf die +/- Tasten gelegt?
Falls nicht, dann bitte auch auf die +/- Tasten legen.

**Comment by FrederikOmlor** [comment]
Numpad + / - wurde hinzugefügt.

**Comment by PaulGuillaumonMuT** [comment]
not fixed.
In der PC-Version 25.04.2024 kann man nicht mit +/- Numpad oder Mausrad zoomen.

**Comment by michaelblatz** [comment]
Das kann ich nicht ganz nachvollziehen. Habe gerade eben nochmal den Build getestet und kann mit beiden Eingabemethoden zoomen

**Comment by PaulGuillaumonMuT** [comment]
Tut mir leid, das hatte ich nicht ausführlich genug erklärt.
Im Tutorial 1 kann man jetzt per Mausrad und +/- Numpad zoomen.
Aber im eigentlichen Spiel funktioniert es nicht mit Mausrad oder +/- Numpad zu zoomen.

**Comment by FrederikOmlor** [comment]
@PaulGuillaumonMuT Ich kann den Fehler leider auch in meinem eigenen Build nicht reproduzieren.
Könntest Du sicherstellen, dass Du das Zoomen direkt zu Beginn des Spiel testest, sodass wir ausschließen können,
dass es sich um einen Bug  durch ein anderes Problem (z.B. ein Popup) handelt?

**Comment by FrederikOmlor** [comment]
Hast Du zufälligerweise ein Keyboard mit US Layout (QWERTY)? Oder Deine Systemsprache auf US/EN ?
Ich kann den Fehler nämlich weiterhin nicht reproduzieren, es gibt jedoch die Möglichkeit, dass das an einem Unity-internen Bug liegt, der abhängig vom Keyboard Layout ist...

**Comment by PaulGuillaumonMuT** [comment]
Hmm, nicht, dass ich wüsste. Laut Windows-Angaben alles auf Deutsch eingestellt.
<img width="468" alt="image" src="https://github.com/Korion-Interactive/scotland-yard/assets/86236228/9cc44b47-e2af-4737-b744-cbcdb7b50e8b">

**Comment by PaulGuillaumonMuT** [comment]
Ich hab das gerade auf einem anderen PC geprüft.
Hier tritt genau das gleiche Verhalten auf.
Sobald ich als menschlicher Spieler mit Mr. X an der Reihe bin, kann ich nicht zoomen.
Mit einem Detektiv geht es.

**Comment by PaulGuillaumonMuT** [comment]
Ich hab noch auf einem 3. PC getestet.
Hier auch das gleiche Verhalten.

Aber ich hab herausgefunden woran es liegt.

Sobald kein Gamepad an den PC angeschlossen ist, dann tritt der Fehler auf.
Schließe ich ein Gamepad an, starte Scotland Yard neu, dann klappt das zoomen mit Maus und Tastatur auch bei Mr. X.
Verhalten bei allen 3 PC gleich.

D.h. es hängt davon ab, ob ein Gamepad angeschlossen ist oder nicht.

**Comment by FrederikOmlor** [comment]
Super vielen Dank, das war der entscheidende Hinweis! Nun sollte es klappen!
