### ISSUE TITLE
von Ravensburger - Anpassungen der Spielerkarten / -spielfiguren auf dem Brett aufgrund Farbenbezug in den Texten

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#30]
In vereinzelten Texten wird Bezug auf die Farben der Spielfiguren genommen (z. B. Tutorial von Mr. X „Mister X wird immer von der weißen Spielfigur repräsentiert.“). Durch die neuen Spielerbilder sieht man die Farbe nur noch am Spielfeldrand unten und nicht mehr oben auf der Plastikfigur selbst. Ggf. müsste man dem Spielerbild noch einen farbigen Rahmen geben oder anderweitig in der entsprechenden Farbe markieren, damit das wieder eindeutiger wird.

**Comment by PaulGuillaumonMuT** [comment]
Sicherheitshalber...wird das wie von Ravensburger vorgeschlagen grafisch umgesetzt? Und es werden keine Textänderungen benötigt.
Korrekt?

**Comment by michaelblatz** [comment]
sorry, hab das überlesen. Keine Textänderung sondern weißer Rahmen um Mr.X.
Vielleicht müsste noch eine Umrandung hinzugefügt werden, um es besser vom Hintergrund abzuheben.
