### ISSUE TITLE
Switch - Play on a single controller - nur 1 menschlicher Mitspieler möglich

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#42]
Nach Auswahl von "Play on a single controller" kann man im Player Selection Menü nur bei einem der Spielfiguren einen menschlichen Spieler einstellen.
Die anderen Spieler kann man nur auf CPU oder OFF stellen.

Bei "Play on a single controller" sollte man aber mehrere menschliche Spieler nacheinander spielen können, oder?

**Comment by FrederikOmlor** [comment]
Siehe #58
