### ISSUE TITLE
von Ravensburger - zwischen 29 und 55 Taxi nutzbar

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#44]
Obwohl zwischen 29 und 55 keine Taxilinie existiert, konnte ich dort als Mr. X das Taxi benutzen. Das sollte nicht sein. Bitte alle Linien dahingehend überprüfen.

**Comment by PaulGuillaumonMuT** [comment]
Die speziell angegebene Situation 29 -> 55 Taxi ist behoben.

Bitte aber bestätigen, dass ihr intern alle anderen Haltestellen geprüft habt, damit das bei allen Haltestellen übereinstimmt, dass man nur Tickets zu den passenden dargestellten Verbindungen aufm dem Stadtplan benutzen kann.

**Comment by michaelblatz** [comment]
Es ist bei aktuellen Aufbau kaum machbar, das ganze im Editor nachzuvollziehen. Im Projekt werden für die Stationen eigene Arten der Anzeige von Optionen genutzt. Das sorgt dafür, dass Unity in der genutzten Version dauerharf abstürzt bei der Kontrolle der Verbindungen. Daher habe ich es aufwändig über das Spielen der Stationen geprüft und konnte nun keine falsche Zuweisung mehr erkennen. Das war meiner Beobachtung nach die einzige Stelle.
