### ISSUE TITLE
von Ravensburger - warum nur 4 menschliche Spieler?

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#48]
Warum können insgesamt nur 4 Spieler spielen und nicht 6 das Brettspiel ist ja für 2-6 Spieler

**Comment by FrederikOmlor** [comment]
Im HotSeat Modus sind nun bis zu 6 Spieler möglich!

**Comment by PaulGuillaumonMuT** [comment]
Reopened, damit ich das gegebenenfalls im nächsten Build nochmal prüfen kann.
