### ISSUE TITLE
Ravensburger - Mr.X kaum zu erkennen

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#51]
Mr. X Figur ist kaum zu erkennen, wenn sie sich zeigen muss.

**Comment by michaelblatz** [comment]
@PaulGuillaumonMuT Kurze Nachfrage: Geht es hier um die halbtransparente (gestrichelte Linie)-Version von Mr X?
Wäre es in Ordnung, die gestrichelte Linie in dem Fall schwarz zu färben?

**Comment by PaulGuillaumonMuT** [comment]
Hier das Feedback von Ravensburger:
"es handelt sich um die transparente Figur von Mr. X auf dem Spielplan.
Ich finde die ist teilweise erst durch längeres Suchen zu finden. Das muss ja nicht sein, sie ist ja in dem Moment sichtbar. Eine schwarze Umrandung könnte hier m.M.n. absolut helfen."

Hier der Screenshot:
![image](https://github.com/Korion-Interactive/scotland-yard/assets/86236228/68575be3-bdf7-48b4-ae6e-ff652a3aa7cb)

PG:
Bei den anderen Spielerfiguren/Spielsteinen werden ja die "aufgesteckten Portraitkärtchen" mit auf den Spielfiguren/Spielsteinen angezeigt.
Laut Screenshot bei Mr. X / Mrs. X aber nicht. Ich finde die entsprechenden "aufgesteckten Portraitkärtchen" sollten aber dort unbedingt auch mit angezeigt werden.

Frage:
Könnte man zusätzlich auch noch einen allgemeinen Grafikeffekt hinzufügen, ähnlich dem für die Figur, die jetzt am Zug ist, damit Mr.X/Mrs.X allgemein deutlicher sichtbar ist.

**Comment by michaelblatz** [comment]
@PaulGuillaumonMuT meinst du mit deiner Frage, ob die Figur so aussehen könnte, wie die Mr X-Figur wenn Mr X am Zug ist? (die Basis mit Portrait-Plättchen)

**Comment by PaulGuillaumonMuT** [comment]
Jein. 
Wenn einer der Kommissare am Zug ist, dann ist unten an der Basis auch die weiße rotierende Animation, wie bei Mr. X/Mrs. X.
D.h. das sollte auch so bei Mr. X / Mrs. X sein, wenn die sich zeigen.
Aber zusätzlich sollte auch noch der Grafikeffekt vorhanden sein, der angezeigt wird wenn ein menschlicher Kommissar am Zug ist. Dann hat die Spielfigur einen langgezogenen gelglichen Schimmer nach oben. 
Dieser Effekt sollte dann auch bei Mr. X / Mrs. X mit angezeigt werden, wenn die sich zeigen müssen.
Damit würde man die sehr gut auf der Karten erkennen/finden.

**Comment by michaelblatz** [comment]
Achso! Jetzt habe ich verstanden, was du meinst. Das kann man grundsätzlich machen. 
Wir sollten uns aber zwei Dinge überlegen:
1. Macht es wirklich einen Unterschied, ob es der menschliche Mr X ist oder nicht? Wenn wir den Effekt anzeigen, würde ich ihn immer anzeigen, ob Mr X von Menschen oder KI gespielt wird.
2. Sollten wir evtl. eine andere Farbe wählen? Da die Figur von Mr X immer stehen bleibt, würde der Effekt ja entsprechend auch immer angezeigt, sobald sich Mr X einmal zeigt. Wenn wir also den Effekt anzeigen, sollten wir vermeiden, dass der Spieler eher sogar an Überblick verliert, weil plötzlich zwei gleichartige Markierungen auf dem Spielplan zu finden sind.

**Comment by PaulGuillaumonMuT** [comment]
1. Es macht keinen Unterschied, ob es ein menschlicher Mr. X oder KI Mr. X ist. In beiden Fällen sollte Mr. X optisch genau gleich dargestellt werden und gut sichtbar.
2. Ja, sehr guter Einwand. Die Farbe des Effekts sollte dann anders sein, damit der Effekt sich deutlich von den Effekten der Spielfiguren unterscheidet.
