### ISSUE TITLE
von Ravensburger - Farbe der Haltestellen

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#54]
Farbe der Haltestellen:
Bushaltestellen – Türkis
Taxi – Gelb
Underground – Rot
Bei einer Haltestelle mit verschiedenen Linienfarben – alle benötigten Farben

Auch die Tickets in den Farben anzeigen.

Und auch in den Regeln die Beschreibung anpassen.

PG: Da ich in den Regeln nicht drinstecke und das Brettspiel nicht kenne...@Michael, kannst du mit den Infos von Ravensburger was anfangen? Also was aufgrund des Feedbacks alles geändert werden muss?

"Bushaltestellen – Türkis
Taxi – Gelb
Underground – Rot"
Das ist aktuell grafisch so umgesetzt, oder?

"Bei einer Haltestelle mit verschiedenen Linienfarben – alle benötigten Farben"
Weißt du, was damit gemeint ist bzw. was für Änderungen gemacht werden müssen?

"Auch die Tickets in den Farben anzeigen."
Weißt du, was damit gemeint ist bzw. was für Änderungen gemacht werden müssen?

"Und auch in den Regeln die Beschreibung anpassen."
Damit sind Anpassungen in den Lokatexten gemeint, korrekt.
In der App-Version sind die Farbzuordnungen wohl anders, als auf dem aktuellen Brettspiel.
In der aktuellen Loka
Taxi - Gelb
Underground - Blau gestrichelt
Bus - Rot
D.h. Underground und Bus haben in der alten App andere Farben als in der neuen Brettspielvariante.
Grafisch habt ihr das entsprechend schon korrekt drin in der App?
Die Textänderungen mach ich dann.
Korrekt?

**Comment by michaelblatz** [comment]
Hallo Paul,
die Tickets sind wohl etwas hinten runtergefallen. Das liefern wir schnellstmöglich nach.

**Comment by michaelblatz** [comment]
@PaulGuillaumonMuT Ich bin etwas uneins, was die Umsetzung hier angeht. Die Haltestellen in der App repräsentieren eher die Logos von London Bus und London Subway. Das war also schon damals wohl ein bewusster Bruch mit dem Spielplan des Brettspiels. Meine Idee wäre in dem Fall eher, nicht die Haltestellen auszutauschen, sondern die Hintergründe der Tickets. Ansonsten müssten wir die Optik der Haltestellen in eine komplett neue Richtung denken. Denn die Icons auf den Tickets und in der gesamten UI repräsentieren die Optik der Haltestellen.
Mein Vorschlag in kurz: Haltestellen samt Icons bleiben gleich, es werden nur die jeweiligen Hintergründe angepasst. Zwei Beispiele habe ich direkt hier angehängt, damit du es dir vorstellen kannst.
![image](https://github.com/Korion-Interactive/scotland-yard/assets/42408911/4ecb66b6-8794-4abc-b65f-270fa81ab6dd)
![image](https://github.com/Korion-Interactive/scotland-yard/assets/42408911/5c2dc23c-8703-487d-bbd6-04766225bc3f)

**Comment by PaulGuillaumonMuT** [comment]
Ich hab dir eine Mail geschickt mit Valentin von Ravensburger auf CC.
Es wäre besser, wenn du das mit Valentin klärst, da ich sein Feedback im Prinzip nicht verstehe, was genau wo wie überhaupt geändert werden soll.

**Comment by michaelblatz** [comment]
Ich schaffe das aufgrund der späten Antwort vermutlich nicht mehr heute, liefere aber schnellstmöglich nach

**Comment by PaulGuillaumonMuT** [comment]
Ich gehe davon aus, dass es so geändert wurde, wie mit Valentin besprochen.
Wie gesagt konnte ich dem Thema relativ schnell gedanklich nicht mehr folgen. ;-)
Daher mache ich das Ticket zu und gegebenenfalls wieder öffnen, falls Valentin bei der Freigabeversion das Thema doch nochmal anspricht.
