### ISSUE TITLE
Fragen zu unterschiedliche Spielregeln

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#55]
Sicherheitshalber...

1. es gibt wohl unterschiedliche Spielregeln, abhängig davon wie viele menschliche Spieler mitspielen.
Ist das in der "alten" App schon berücksichtigt?

2. Ist in der "alten" App schon die Spielvariante "Einsteigerspiel" berücksichtigt?
Hier die entsprechende Spielanleitung:
https://www.ravensburger.de/spieleanleitungen/ecm/Spielanleitungen/26602%20anl%201326321.pdf

**Comment by michaelblatz** [comment]
Zu 1: Das muss ich noch nachschauen. Dazu benötigen wir noch die Anleitung. Ich glaube, die angehängte Datei ist das Switch-Cover aber keine Anleitung. In wie fern ändern sich die Spielregeln bei unterschiedlicher Spielerzahl?
Zu 2: In der alten App gibt es keine Variante "Einsteigerspiel".

Generell zu beiden Punkten: In unsere Planung ist damals eingeflossen, dass sich am Spielablauf per se nichts ändert. Größere Änderungen am Spielablauf waren hier nicht vorgesehen. Wenn wir die Anleitung haben, können wir hier aber eine Einschätzung geben, ob das leicht umzusetzen ist oder nicht. Eine separate Spielvariante wäre aber zumindest auf den ersten Blick ein erheblicher Aufwand, so wie das Spiel gerade aufgesetzt ist.

**Comment by PaulGuillaumonMuT** [comment]
Zu 2.: Hatte ich mir schon gedacht.
Zu 1.: Anleitung hier https://www.ravensburger.de/spieleanleitungen/ecm/Spielanleitungen/26602%20anl%201326321.pdf

Mir geht es nur darum zu wissen, ob das schon in der alten App und damit auch in der Portierung vorhanden ist.
Nur falls Ravensburger plötzlich anmerkt, dass diese Spiel-Varianten nicht in der Portierung vorhanden sind.

Es ist nicht geplant, dass diese Varianten neu mit hinzukommen sollen.

**Comment by michaelblatz** [comment]
Es ist nichts entsprechendes umgesetzt. Man erhält nur eine Warnung, wenn man mit zu wenigen Spielern spielt, kann aber dennoch spielen. Eine extra Variante ist nicht umgesetzt

**Comment by PaulGuillaumonMuT** [comment]
Super, vielen Dank fürs Nachschauen!
