### ISSUE TITLE
von Ravensburger, PC, Multiplayer - mehrere menschliche Spieler deaktiviert

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#58]
Scheinbar habt ihr im aktuellen Build den Multiplayer-Modus mehrerer menschlicher Spieler an einem PC deaktiviert. Ich kann nur noch maximal einen Detektiv oder alternativ als MR. X spielen. Der Rest kann nur deaktiviert oder mittels KI aufgefüllt werden. Im letzten Build konnte ich noch mehrere Slots mit menschlichen Mitspielern füllen. Ist das ein Fehler oder so gewollt? Ich habe das parallel in der Switch-Version (V 2.6) getestet, da kann ich insgesamt bis zu 4 menschliche Spieler hinzufügen.

**Comment by michaelblatz** [comment]
Hallo Paul,
den Fehler haben wir bemerkt und behoben.
Ebenso wie das Einstellen von bis zu 6 Spielern, wenn man an nur einem Controller spielt
