### ISSUE TITLE
von Ravensburger, Switch - Scrollen mit R-Stick zu langsam

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#63]
-	09.04.2024: Das Verschieben des Bildschirms mit dem rechten Analog-Stick dürfte gern schneller vonstattengehen. Es dauert schon ziemlich lange, um über das Spielfeld zu scrollen.

**Comment by FrederikOmlor** [comment]
@PaulGuillaumonMuT Passt die Geschwindigkeit so?
