### ISSUE TITLE
von Ravensburger - Button-Anzeige in den Menüs ist nicht konsistent

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#71]
-	09.04.2024: Die Button-Anzeige ist aktuell in den Menüs noch immer nicht konsistent. Wählt man z. B. „Neues Spiel“, dann wird im nächsten Menü links oben „B für Zurück“ angezeigt. Tippt man nun auf „Einführung“, fehlt im nächsten Untermenü links oben das „B“.

**Comment by michaelblatz** [comment]
Done
