### ISSUE TITLE
von Ravensburger - vereinzelt Popups bzw. Funktionen nur mit Touch steuerbar

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#72]
-	09.04.2024: In den Tutorials gibt es noch vereinzelte Hinweis-Popups bzw. Funktionen, die wohl nur mittels Touch ausgeführt werden können (z. B. die Zug-Historie ein- bzw. ausblenden). Ich konnte die mit dem Kreis-Cursor nicht ausklappen. Erst mittels Touch mit einem Finger. Gibt ggf. noch andere solche Stellen, habe jetzt nicht alles in allen Tutorials durchprobiert. 

Update: Konnte das Zug-Historie-Menü auch während eines normalen Spiels nicht mit dem virtuelle Mauspfeil/Cursor ein- bzw. ausklappen, das geht nur mit der „-„-Taste.

**Comment by michaelblatz** [comment]
Das Verhalten, dass es nur mit Touch und der - Taste gesteuert werden kann, ist gewünscht. Zwecks fehlender Steuerung der GUI mit virtuellem Cursor bitte die Antwort hier beachten: https://github.com/Korion-Interactive/scotland-yard/issues/73

**Comment by michaelblatz** [comment]
@PaulGuillaumonMuT ist das mit #73 gelöst? 
Popups dürfen nicht mit dem virtuellen Cursor gesteuert werden. Es wurde noch ein Glyph neben dem "OK" in den Tutorial-Popups angezeigt

**Comment by PaulGuillaumonMuT** [comment]
Ob das gelöst ist, kann ich erst sagen, wenn ich mir das in der neuen Version anschaue.
