### ISSUE TITLE
von Ravensburger - Ingame Einstellungs-Menü kann nur mit Touchscreen geöffnet werden

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#73]
-	09.04.2024: Selbiges Problem auch mit dem Einstellungs-Menü innerhalb eines laufenden Spiels. Ein „Tap“ auf das Zahnrad öffnet das Menü, ein klick mit dem virtuellen Cursor funktioniert aber nicht. Die Leiste unten mit den verschiedenen Detektiven/Mr. X lässt sich hingegen aber korrekt mittels des virtuellen Mauspfeils anklicken.

**Comment by michaelblatz** [comment]
Generell: Mit dem eingesetzten GUI-System ist es nicht einfach möglich, die GUI mit dem virtuellen Cursor zu steuern. Warum es bei der unteren Leiste funktioniert, liegt daran, dass es mit unterschiedlichen Kameras und Kameratiefen aufgenommen wird. Kurz gesagt: Mit dem UI System sollte der virtuelle Cursor nicht mit eingerechnet werden. Es ist allerdings auch unüblich, dass bei Spielen mit dem virtuellen Cursor die GUI gesteuert werden kann. Bereits bei DVL haben wir hier einen Sonderfall behandelt. Da es mit er Unity-eigenen GUI gemacht wurde, war das allerdings möglich.


Wurde hier beachtet, dass die Glyphs - und + an der GUI waren und das Einstellungs-Menü mittels + geöffnet werden kann?

**Comment by michaelblatz** [comment]
War schon etwas Aufwand und nur sehr "hacky" zu machen, ist aber integriert und sollte nun für den Optionen-Button und den Move-History-Button laufen

**Comment by PaulGuillaumonMuT** [comment]
Super, vielen Dank!
