### ISSUE TITLE
von Ravensburger - Extras/Regeln - Texte lassen sich nicht mit Controller scrollen

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#74]
-	09.04.2024: Bei den Regeln (unter Extras) kann man die Textfelder rechts mit dem Joypad nicht scrollen, wenn die länger sind als der sichtbare Bereich. Mir mittels Touch lässt sich der Text aktuell scrollen. Selbiges Problem existiert auch am PC mit Xbox Series Joypad.

**Comment by FrederikOmlor** [comment]
Scrollen wurde für Controller und Mausrad hinzugefügt und sollte im nächsten Build verfügbar sein.

**Comment by PaulGuillaumonMuT** [comment]
not fixed.
Switch: Scrollen der Texte unter Extras, Regeln ist in der Version 25.04.2024 nicht mit dem rechten Stick möglich.
PC: Scrolling per Mausrad habe ich noch nicht geprüft, da Switch höhere Prio hat.

**Comment by FrederikOmlor** [comment]
Müsste nun für Switch funktionieren.
