### ISSUE TITLE
Hauptmenü - Nebentitel ist immer "Hunting Mister X"

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#78]
Im Hauptmenü wird unter dem Scotland Yard Logo als Nebentitel in jeder  Sprache der EN-Text "Hunting Mister X" angezeigt.

Bitte anpassen:
EN: HUNTING MISTER X
DE: AUF DER JAGD NACH MISTER X
FR: A LA POURSUITE DE MISTER X
IT: A CACCIA DI MISTER X
ES: LA BÚSQUEDA DE MISTER X

**Comment by michaelblatz** [comment]
@PaulGuillaumonMuT Der Lauftext ist als Bild eingebaut. Wir haben leider die entsprechende Schriftart nicht. Sollen wir den Titel dann überhaupt anzeigen oder nur durch eine neue Schriftart einsetzen?

**Comment by PaulGuillaumonMuT** [comment]
Hier 2 Links zu Assets von Ravensburger - 28 Tage gültig:
https://my.hidrive.com/share/0d.1y9azeu
https://my.hidrive.com/share/9qir3877b6

Hier sind u.a. die aktuellen Packungen im horizontaler und vertikaler Ausrichtung vorhanden und auch wie der Nebentitel aktuell aussieht.
Und es sind auch diverse Fonts mit dabei.
Könnt ihr anhand der Grafiken und Fonts von Ravensburger die benötigten Grafiken entsprechend erstellen?

Falls es mit dem gescrollten Text mit neuem Font aber nicht gut aussehen würde, dann könnte man auch überlegen,  ob  wir den gescrollten Text überhaupt brauchen oder den Nebentext einfach nur als feste Grafik, so wie auf den Spiele-Packungen unter dem Logo anzeigen.

**Comment by PaulGuillaumonMuT** [comment]
Sicherheitshalber...oben im Start-Ticket die Texte der Nebentitel geändert und ES hinzugefügt.

**Comment by PaulGuillaumonMuT** [comment]
Gerade aufgefallen.
Im EN ist im Hauptmenü nicht der oben angegebene Nebentitel verwendet.

Es wird der Text
HUNTING MR X
angezeigt statt
HUNTING MISTER X

Bitte korrigieren und bitte alle Texte oben nochmals prüfen, ob die in allen Sprachen exakt wie oben angegeben eingebaut wurden.

**Comment by PaulGuillaumonMuT** [comment]
Oh, gerade in der PC-Version festgestellt.
Der EN Text ist ja immer noch
HUNTING MR X
statt
HUNTING MISTER X 

Hm, seltsam, dass Ravensburger das in der Switch-Version nicht angemerkt hat.

Egal. 
Ich schließe das Ticket und dann schaun wir mal ob Ravensburger das bei der PC-Version anmerkt.
