### ISSUE TITLE
Menü "Spielmodus" - Icons der beiden Controller-Varianten verwirrend

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#93]
Im Menü Spielmodus bei dir Auswahl, ob man mit einem  Controller zum Herumreichen oder jeder mit eigenem Controller spielen möchte...die verwendeten Buttongrafiken machen nicht wirklich deutlich, welche Controller-Spielart es ist.

Vor allem der Button in der Mitte (gelbe und weiße Spielfigur mit den grünen Pfeilen) kann auch so interpretiert werden, dass es einen Wechsel bedeutet aufgrund der Pfeile. Und der andere Button ohne Pfeile kein Wechsel des Controllers. Was ja aber falsch wäre von der aktuellen Funktionalität.

Könntet ihr die Grafik für den mittleren Button anpassen.
Und zwar die grünen Pfeile entfernen.
Dann wie auf dem linken Button eine rote und schwarze Spielfigur und über jeder Spielfigur das blaue Controller-Icon.
Damit wäre es klar, dass beim linken Button nur 1 Controller verwendet wird und beim mittleren Button mehrere Controller.

**Comment by michaelblatz** [comment]
Da wir keine Originalgrafiken vorliegen haben und somit keine Texturatlanten neu anordnen können, ist das mit dem blauen Controller-Icon nicht möglich. Das liegt u.a. daran, dass wir die originale Grafik nicht nutzen können. Stattdessen habe ich aber die Grafik ausgetauscht und Controller-Icons darübergesetzt. Ich denke, damit wird es auch klar. Das Icon ist dasselbe.
