### ISSUE TITLE
Frage - 1 Joy-Con horizontal pro Spieler möglich?

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#94]
Ich habe es nicht geschafft die Controller so mit dem Spiel zu verbinden, dass man mit 1 Joy-Con-Paar, also mit 2 einzelnen Joy-Cons diese für 2 Spieler verwenden kann.
Also quasi jeder Spieler hat 1 Joy-Con horizontal.

Ist es aktuell nicht implementiert auch mit 1 Controller horizontal spielen zu können?
Das wäre nämlich extrem wichtig, denn wer hat den schon so viele Joy-Con Paare zu Hause.

**Comment by michaelblatz** [comment]
@PaulGuillaumonMuT Genau aus dem Grund haben wir ja die Option, mit nur einem Controller zu spielen. Horizontal ist kaum möglich, da wir Gameplay-Funktionen sowohl auf den Trigger-Buttons (also kein Zoom möglich) als auch dem rechten Stick haben (also keine Kamerabewegung). Eine Steuerung mit einem einzelnen Joy-Con ist so leider nicht machbar.

**Comment by PaulGuillaumonMuT** [comment]
Stimmt, die ganzen Funktionen hätte man auf ein Joy-Con schlecht untergebracht.
