### ISSUE TITLE
Spracheinstellung wird nicht gespeichert

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#96]
App starten.
Im Hauptmenü oben DE einstellen.
App beenden.
App neu starten.
App startet auf EN, nicht auf DE.

**Comment by PaulGuillaumonMuT** [comment]
not fixed.
Verhält sich in der Version 25.04.2024 noch genau so, wie oben beschrieben.

**Comment by FrederikOmlor** [comment]
@PaulGuillaumonMuT  Auf welcher Plattform hattest Du denn getestet?
Ich kann es weder im Editor noch in meinem eigenen PC Build reproduzieren.

**Comment by PaulGuillaumonMuT** [comment]
Tut mir leid, die Info hatte ich vergessen.
Problem tritt auf der Switch auf

**Comment by FrederikOmlor** [comment]
Entschuldige die Verwirrung :) 
Ich habe Dir den Issue zugewiesen, weil ich den Fehler doch noch finden konnte und ihn gefixt habe. Er sollte im nächsten Build nicht mehr auftreten.
