### ISSUE TITLE
Hauptmenü - UI-Logik für "Optionen" und "Extras" verwirrend

### ISSUE THREAD

**Issue by PaulGuillaumonMuT** [Korion-Interactive/scotland-yard#98]
Im Hauptmenü ist die UI-Logik bei Optionen und Extras verwirrend.

1. Wenn man Optionen markiert ist der Button Schwarz. Drückt man jetzt A öffnet sich das Untermenü nach oben. Der Button für Optionen wird jetzt aber Blau und blaue Schrift. Der Button sollte aber weiterhin schwarz bleiben, da er aktuell ja markiert ist.
2. Bewegt man den Stick nach oben wird Musik markiert und der Button "Musik" ändert sich zu Schwarz und blauer Schrift. Das ist OK. Aber der "Optionen"-Button wird jetzt Schwarz, so als wäre dieser ausgewählt. Aber der Button müsste blau werden, da er nicht ausgewählt ist.
3. Bewegt man den Stick jetzt nach unten auf Optionen und nach Rechts auf "Neues Spiel" bleibt der Button "Optionen" jedoch schwarz und ausgeklappt.

Bei Extras verhält es sich im Prinzip genau so. Nur mit dem Unterschied wenn Extras ausgeklappt ist und man "Extras" markiert, dann ist der Button Schwarz und blauer Text. Das ist OK. Wenn man dann nach oben auf "Regeln" geht, dann bleibt der "Extras"-Button aber weiterhin schwarz, also auch so wie bei "Optionen".

Das Verhalten ist nicht konsistent und verwirrend.

**Comment by michaelblatz** [comment]
Ich habe 1 und 3 umgesetzt. Den 2. Punkt konnte ich leider nicht ganz nachvollziehen. Welcher Button müsste blau sein, weil er nicht ausgewählt ist?

Schau dir die neuste Version am besten mal an. Vielleicht passt ja schon alles, da die Schrift des Optionen-Button auch bei Markierung jetzt blau wird (gleiches bei Extras)

**Comment by michaelblatz** [comment]
Mir ist aufgefallen, dass das einklappen noch nicht korrekt funktioniert hat. Das UI System hat beim Überführen Referenzen rausgekickt. Das ist leider eine immer wieder aufkommende Sache, weshalb wir UI-Anpassungen vermeiden, wo möglich. Ein Hotfix für die Switch kommt heute noch
